##########################################################
# .aider.conf.yml
# This file lists the valid configuration entries.
# Place in home dir, or at the root of your git repo.
##########################################################

# :::'###::::'####:'########::'########:'########::
# ::'## ##:::. ##:: ##.... ##: ##.....:: ##.... ##:
# :'##:. ##::: ##:: ##:::: ##: ##::::::: ##:::: ##:
# '##:::. ##:: ##:: ##:::: ##: ######::: ########::
#  #########:: ##:: ##:::: ##: ##...:::: ##.. ##:::
#  ##.... ##:: ##:: ##:::: ##: ##::::::: ##::. ##::
#  ##:::: ##:'####: ########:: ########: ##:::. ##:
# ..:::::..::....::........:::........::..:::::..::

##########################################################

# options:

## show this help message and exit
#help: xxx

#############
# Main model:

## Specify the model to use for the main chat
#model: xxx

#################
# Model settings:

## List known models which match the (partial) MODEL name
#list-models: xxx

## Specify a file with aider model settings for unknown models
#model-settings-file: .aider.model.settings.yml

## Use architect edit format for the main chat
architect: true

## Specify the model to use for commit messages and chat history summarization (default depends on --model)
#weak-model: xxx

## Specify the model to use for editor tasks (default depends on --model)
#editor-model: xxx

#################
# Cache settings:

## Enable caching of prompts (default: False)
cache-prompts: true

## Number of times to ping at 5min intervals to keep prompt cache warm (default: 0)
#cache-keepalive-pings: false

################
# History Files:

## Specify the chat input history file (default: .aider.input.history)
#input-history-file: .aider.input.history

## Specify the chat history file (default: .aider.chat.history.md)
#chat-history-file: .aider.chat.history.md

## Restore the previous chat history messages (default: False)
#restore-chat-history: false

## Log the conversation with the LLM to this file (for example, .aider.llm.history)
llm-history-file: .aider.llm.history

##################
# Output settings:

## Use colors suitable for a dark terminal background (default: False)
dark-mode: true

###############
# Git settings:

## Attribute aider code changes in the git author name (default: True)
attribute-author: false

## Specify a custom prompt for generating commit messages
commit-prompt: ./config/cz.config.mjs

## Enable/disable watching files for ai coding comments (default: False)
watch-files: true

########################
# Fixing and committing:

## Lint and fix provided files, or dirty files if none provided
lint: true

## Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times)

lint-cmd: pnpm lint

## Specify multiple values like this:

#lint-cmd:
#  - xxx
#  - yyy
#  - zzz

## Enable/disable automatic linting after changes (default: True)
auto-lint: true

## Specify command to run tests
#test-cmd: pnpm test

## Enable/disable automatic testing after changes (default: False)
#auto-test: true

## Run tests, fix problems found and then exit
#test: true

########
# Modes:

## Run aider in your browser (default: False)
#gui: false

## Enable automatic copy/paste of chat between aider and web UI (default: False)
#copy-paste: false

#################
# Voice settings:

## Specify the input device name for voice recording
#voice-input-device: xxx

################
# Other settings:

## specify a read-only file (can be used multiple times)
#read: xxx

## Specify multiple values like this:
#read:
#  - xxx
#  - yyy
#  - zzz

## Specify which editor to use for the /editor command
editor: zed --wait

