repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - args:
    - --maxkb=500
    id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - args:
    - --line-length=88
    id: black
    language_version: python3
  repo: https://github.com/psf/black
  rev: 23.9.1
- hooks:
  - additional_dependencies:
    - flake8-docstrings
    args:
    - --max-line-length=88
    exclude: ^(venv/|docs/)
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 6.1.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.30.0
