grid-rows:4

rectangle: {
  shape: rectangle

  rect: |md
	  Standard Process
  |
}

square: {
  shape: square

  sq: |md
	  Tagged

		Process
  |
}

page: {
  shape: page

  pg: |md
	  Tagged

		Document
  |
}

parallelogram: {
  shape: parallelogram

  pl: |md
	  Input or Output
  |
}

document: {
  shape: document

  doc: |md
	  Represents

		a Document
  |
}

cylinder: {
  shape: cylinder

  cyl: |md
	  Database

		or Disk Storage
  |
}

queue: {
  shape: queue

  q: |md
	  Direct Access Storage
  |
}

package: {
  shape: package

  pkg: |md
	  File Operations
  |
}

step: {
  shape: step

  st: |md
	  Prepare Conditional
  |
}

callout: {
  shape: callout

  call: |md
	  Important Commnent

		or Note
  |
}

stored_data: {
  shape: stored_data

  call: |md
	  persisted

		data
  |
}

person: {
  shape: person

  call: |md
	  Actor
  |
}

diamond: {
  shape: diamond

  call: |md
	Decision

	Step
  |

}

hexagon: {
  shape: hexagon

  call: |md
	  Conditional

	  Step
  |

}
circle: {
  shape: circle

  call: |md
	  Start
  |

}

oval: {
  shape: oval

  ov: |md
	  event occurrance
  |

}

cloud: {
  shape: cloud

  cld: |md
	  Cloud Node

	  or service
	|

}



# text
# image
# sql_table
# class