
version: '3.8'

services:
  workspace:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - ~/.gitconfig:/home/vscode/.gitconfig
    command: sleep infinity

volumes:
  node_modules: