name: autofix.ci  # needed to securely identify the workflow

on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      # Setup Node.js and pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest'
          cache: 'pnpm'


      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Setup Python
      - name: Install Python 3.12
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'
      
      # Run Turbo tasks for linting and formatting
      - name: Lint and Format
        run: pnpm turbo run lint:fix
        
      - name: autofix.ci
        uses: autofix-ci/action@v1.3.1
