name: autofix.ci  # needed to securely identify the workflow

on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      # Setup Node.js and pnpm
      - name: Setup Node.js
        uses: actions/setup-node@8f9cc178b6e843639351e0bd5d638e5fd0a8dec7
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@e303250a2450c28e843bf798954fac81d4835f68
        with:
          version: latest

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Setup Python
      - name: Install Python 3.12
        uses: actions/setup-python@v1928ae624dc06094d8c65f021a4700ea8fa56b9d
        with:
          python-version: '3.12'

      # Run Turbo tasks for linting and formatting
      - name: Lint and Format
        run: pnpm turbo run lint:fix
        
      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
