name: Main
on:
  # Run on pull request, so that the PR can be analyzed.
  pull_request:
  push:
    branches:
      - main
  merge_group:
  # Run weekly, so that the baseline AppMap artifact does not expire.
#   # schedule:
#   #   - cron: '0 0 * * 0'

# permissions:
#   # Read the baseline artifact in order to perform
#   # the AppMap comparison.
#   actions: read

#   # Commit the AppMap configuration.
#   # If the EndBug/add-and-commit is removed,
#   # this can be changed to 'read'.
#   contents: write

#   # Add check annotations to the source code when
#   # a problem is detected.
#   checks: write

#   # Add a comment to the pull request.
#   pull-requests: write

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env: 
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
      
      - name: Cache turbo build setup
        uses: actions/cache@v4.2.0
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install dependencies
        run: |
          pnpm install -w
          pnpm add -D jest-junit

      - name: Build
        run: pnpm build
      
      # # Begin install-action snippet
      # #
      # - name: Install AppMap tools
      #   id: install-appmap
      #   uses: getappmap/install-action@e03d1221532d7024300b06ba85aef35661f59f09
      #   with:
      #     project-type: pip
      #     build-patch-file: false

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@a604fba70a846a0ea59e6040ef8a4a4f95015772
      # #
      # # End install-action snippet

      - name: Run tests with coverage
        run: |
          JEST_JUNIT_CLASSNAME="{filepath}" pnpm test -- --coverage --coverageReporters=json-summary --reporters=jest-junit

      # - name: Archive AppMaps
      #   uses: getappmap/archive-action@81f51177646dd89a505299dc31d034defa68f347
      #   with:
      #     revision: ${{ github.event.pull_request.base.sha }}
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          files: coverage/coverage-summary.json

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}