name: Main
on:
  push:
    branches:
      - main
  # Run on pull request, so that the PR can be analyzed.
  pull_request:
  merge_group:
  # Run weekly, so that the baseline AppMap artifact does not expire.
  schedule:
    - cron: '0 0 * * 0'

permissions:
  # Read the baseline artifact in order to perform
  # the AppMap comparison.
  actions: read

  # Commit the AppMap configuration.
  # If the EndBug/add-and-commit is removed,
  # this can be changed to 'read'.
  contents: write

  # Add check annotations to the source code when
  # a problem is detected.
  checks: write

  # Add a comment to the pull request.
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          # Checkout pull request head so that a commit can be made
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install dependencies
        run: |
          pnpm install -w
          pnpm add -D jest-junit
      
      # Begin install-action snippet
      #
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: pip
          build-patch-file: false
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
      #
      # End install-action snippet

      - name: Run tests with coverage
        run: |
          JEST_JUNIT_CLASSNAME="{filepath}" pnpm test -- --coverage --coverageReporters=json-summary --reporters=jest-junit

      - name: Archive AppMaps
        uses: getappmap/archive-action@v1
        with:
          revision: ${{ github.event.pull_request.base.sha }}
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/coverage-summary.json

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}